/** @jsxImportSource @emotion/react */

import Head from 'next/head';
import Layout from '../components/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Bundle Next.js</h1>
        <p>With Emotion, Styled Component and css Prop</p>
        <p css={{ fontStyle: "italic" }}>Plus theme</p>
      </Layout>
    </>
  )
}
